- name: Read .nvmrc
    run: echo ::set-output name=NVMRC::$(cat .nvmrc)
    id: nvm

- name: Build & Test

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    build-test:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ steps.nvm.outputs.NVMRC }}
        - run: npm i yarn
        - run: yarn
        - run: yarn build
        - run: yarn test